version: '3'
services:
  lightsail:
    image: lightsail-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
        - VERSION =${VERSION}
       
    ports:
      - 8000:8000
    command: python app.py

